# TYRANID REQUESTS

GET http://localhost:3000/tyranids

###

GET http://localhost:3000/tyranids/63e851edd0c1826c5d0fa436

###
POST http://localhost:3000/tyranids/add HTTP/1.1
Content-Type: application/json

{
    "hiveFleet": "Behemoth",
    "adaptive": "ob-sec monsters",
    "nullForceOrg": {"models": 3, "unit": "Hive Guard"},
    "hq": [{
            "models": 1, "unit": "Hive Tyrant"
        },
        {
            "models": 1, "unit": "Nuerothrope"
        }],
    "troop": {"models": 10, "unit": "Termagants"}
}

###
DELETE http://localhost:3000/tyranids/delete/63e59b86bc7dad58749ffb34

###
PUT http://localhost:3000/tyranids/update/63e59be917e9275c60efa8cd HTTP/1.1
Content-Type: application/json

{
    "hiveFleet": "Leviathan",
    "adaptive": "ob-sec monsters",
    "nullForceOrg": {"models": 3, "unit": "Hive Guard"},
    "hq": [{
            "models": 1, "unit": "Hive Tyrant"
        },
        {
            "models": 1, "unit": "Nuerothrope"
        }],
    "troop": {"models": 10, "unit": "Termagants"},
    "elite": {"models": 5, "unit": "Genestealers"}
}




###
GET https://cse341-personal-qj62.onrender.com/tyranids

###
GET https://cse341-personal-qj62.onrender.com/tyranids/63e59c7017e9275c60efa8ce

###
POST https://cse341-personal-qj62.onrender.com/tyranids/add HTTP/1.1
Content-Type: application/json

{
    "hiveFleet": "Behemoth",
    "adaptive": "ob-sec monsters",
    "nullForceOrg": {"models": 3, "unit": "Hive Guard"},
    "hq": [{
            "models": 1, "unit": "Hive Tyrant"
        },
        {
            "models": 1, "unit": "Nuerothrope"
        }],
    "troop": {"models": 10, "unit": "Termagants"}
}

###
DELETE https://cse341-personal-qj62.onrender.com/tyranids/delete/63e59c7017e9275c60efa8ce

###
PUT https://cse341-personal-qj62.onrender.com/tyranids/update/63e59c7017e9275c60efa8ce
Content-Type: application/json


{
    "hiveFleet": "Leviathan",
    "adaptive": "ob-sec monsters",
    "nullForceOrg": {"models": 3, "unit": "Hive Guard"},
    "hq": [{
            "models": 1, "unit": "Hive Tyrant"
        },
        {
            "models": 1, "unit": "Nuerothrope"
        }],
    "troop": {"models": 10, "unit": "Termagants"},
    "elite": {"models": 5, "unit": "Genestealers"}
}

###
# WOLVES REQUESTS

GET http://localhost:3000/wolves

###
GET http://localhost:3000/wolves/63e844f121360d41328de1e8

###
POST http://localhost:3000/wolves/add HTTP/1.1
Content-Type: application/json

{
    "hq": [{
            "models": 1, "unit": "Captain"
        },
        {
            "models": 1, "unit": "Chaplain"
        }],
    "troop": {"models": 5, "unit": "Assault Intercessors"},
    "elite": {"models": 5, "unit": "Terminators"},
    "heavySupport": {"models": 1, "unit": "Land Raider"}
}

###
DELETE http://localhost:3000/wolves/delete/63e844f121360d41328de1e8

###
PUT http://localhost:3000/wolves/update/63e844f121360d41328de1e8 HTTP/1.1
Content-Type: application/json

{
    "hq": [{
            "models": 1, "unit": "Captain"
        },
        {
            "models": 1, "unit": "Chaplain"
        }],
    "troop": {"models": 5, "unit": "Assault Intercessors"},
    "elite": {"models": 5, "unit": "Terminators"},
    "heavySupport": {"models": 1, "unit": "Land Raider"},
    "transport": {"models": 1, "unit": "Drop Pod"}
}

###
GET https://cse341-personal-qj62.onrender.com/wolves

###
GET https://cse341-personal-qj62.onrender.com/wolves/63e84f7bd0c1826c5d0fa435

###
POST https://cse341-personal-qj62.onrender.com/wolves/add HTTP/1.1
Content-Type: application/json

{
    "hq": [{
            "models": 1, "unit": "Captain"
        },
        {
            "models": 1, "unit": "Chaplain"
        }],
    "troop": {"models": 5, "unit": "Assault Intercessors"},
    "elite": {"models": 5, "unit": "Terminators"},
    "heavySupport": {"models": 1, "unit": "Land Raider"}
}

###
DELETE https://cse341-personal-qj62.onrender.com/wolves/delete/63e84f7bd0c1826c5d0fa435

###
PUT https://cse341-personal-qj62.onrender.com/wolves/update/63e84f7bd0c1826c5d0fa435
Content-Type: application/json

{
    "hq": [{
            "models": 1, "unit": "Captain"
        },
        {
            "models": 1, "unit": "Chaplain"
        }],
    "troop": {"models": 5, "unit": "Assault Intercessors"},
    "elite": {"models": 5, "unit": "Terminators"},
    "heavySupport": {"models": 1, "unit": "Land Raider"},
    "transport": {"models": 1, "unit": "Drop Pod"}
}